# configs/base_config.yaml

base_training:
  args:
    learning_rate: 0.00005
    per_device_train_batch_size: 16
    per_device_eval_batch_size: 16
    num_train_epochs: 3
    weight_decay: 0.01
    warmup_ratio: 0.0
    evaluation_strategy: "epoch"
    save_strategy: "epoch"
    load_best_model_at_end: true
    metric_for_best_model: "accuracy"
    report_to: "none" # <--- ADD THIS LINE

fish_tuning:
  enabled: true
  num_samples: 128
report_to: "none"
